### ISSUE TITLE
Wilbur Atwater Code Review

### ISSUE THREAD

**Issue by laragursoy** [vishalival/eep153-margaret-reid#2]
Hi! First off, I really like your population of interest and I think it's really unique. I've heard a lot about how people in those regions of the world face high food costs because of their remote locations so it's interesting to see the work you put in.

Maybe I missed something, but I'm not exactly sure what the difference between solution 1 and 2 are - is it that one includes traditional foods and one doesn't? That's what it seems but I wasn't sure. There's also a small typo for the markdown cell with solution 2 (it says grcoery store instead of grocery)

I really do not have anything to say - the code cells are clear and I can see what the purpose of each cell is, and the code works properly. I guess maybe mention why you specifically chose the 35-50 Female age group, but I'm sure you mention that in your presentation anyways. Nice work!

**Comment by vishalival** [comment]
Hey, thanks for your feedback. We greatly appreciate it.

Didn't catch the grocery store typo, so thanks for checking that.

So the difference is traditional foods VS non traditional foods, we wanted to see if including traditional foods in the mix for determining the best solution for those from the Inuit background would make it cheaper/more expensive, since it's very conventional to believe regular American foods may be the cheapest for the most nutrition - but we found that traditional foods were actually cheaper. 

Thank you!!

**Comment by vishalival** [comment]
Issue completed
